### ISSUE TITLE
Move React codebase to 'react' branch

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#1]
Move the current main branch to `react` branch. We will start clean with Next.js and plain CSS for the actual development.

**Comment by tu2-atmanand** [comment]
New `ReactDev` has been created to keep the old codebase as a safe checkpoint.
Also i have submitted an pull request for the new `TestNextJS` branch, if everything looks good, we can merge the branch to the `main` branch.

**Comment by Greeshma2903** [comment]
@tu2-atmanand great
I think we can merge Sanjay's fork into the TestNextJS version then, and keep it all under one repo for now.
