### ISSUE TITLE
feat: What we do section @home

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#10]
- [ ] Card component
- [ ] Seciton Heading

- on hover card: add border-radius

![image](https://github.com/Engicos-Coders-Club/club-official-website/assets/70336930/8fc3463c-e74b-401d-b136-39f70fdd215c)

**Comment by Shriteen** [comment]
We also need design at less width

**Comment by Shridhar-dev** [comment]
I will start working on this
