### ISSUE TITLE
feat: Heading section for pages

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#11]
- Heading
- Description 

![image](https://github.com/Engicos-Coders-Club/club-official-website/assets/70336930/4eb80072-d70a-42ea-a622-6006116a9ed7)

**Comment by SshibamDebnathh** [comment]
what is the issue can you elaborate?

**Comment by Greeshma2903** [comment]
Hey @SshibamDebnathh 
The current issues are being worked on by a Core Team. We will soon open these issues to other contributors once a base setup is done. Keep an eye on the repo, we will make an announcement on our Club channels. Thanks 🙌🏽 

Incase you would like to be part of the team, lmk.
