### ISSUE TITLE
feat: Contact page

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#13]
Build a responsive section based on the design below 👇🏽 

Button linked to the Skill Survey form: https://docs.google.com/forms/u/3/d/e/1FAIpQLSfY24F2SeC1G7SQkKIq9GvUC5-DmIBPZfXPEH7gc096jou8ew/alreadyresponded?usp=send_form

![image](https://github.com/Engicos-Coders-Club/club-official-website/assets/70336930/cc03830b-0e27-4382-bab5-16aa9d87a84f)

**Comment by Quantaindew** [comment]
done 

Rough skeleton added, colors and fonts (and font size) needed to be decided
https://github.com/Engicos-Coders-Club/club-official-website/commit/6d085d5cb8a6bb6235643f356b4dcbf4bc1ac52d

**Comment by Quantaindew** [comment]
added copy to clipboard function
https://github.com/Engicos-Coders-Club/club-official-website/commit/2439114350ae856e8e773dccf3e7adb3c6ac622f
