### ISSUE TITLE
Update the readme in next-ts branch

### ISSUE THREAD

**Issue by tu2-atmanand** [Engicos-Coders-Club/club-official-website#16]
Since `main` and `next-ts` are our main development/showcase branches, its better that we have on both branches similar readme. Change be the done to the 'how to setup' and other neccessary sections/content. Like if current state image can be removed and instead of that, the hosted vercel link can be added.

**Comment by Quantaindew** [comment]
Done

https://github.com/Engicos-Coders-Club/club-official-website/commit/6843d784ed4ca47054e8204ab75d27c4fce27b02
