### ISSUE TITLE
Github Pages to see live changes

### ISSUE THREAD

**Issue by tu2-atmanand** [Engicos-Coders-Club/club-official-website#2]
While our project was in React JS development, i wanted to enable github pages so we could able to see the live updates. 
But since now we will gonna be moving our Dev to Next JS, should we enable the github Pages feature?
I am asking this is because, i want to know how good the integration is between the two.

For reference : https://youtu.be/nded252qxcA

**Comment by Quantaindew** [comment]
+1

**Comment by tu2-atmanand** [comment]
Finally got build after two fails.
The website is live at : https://engicos-coders-club.github.io/club-official-website
