### ISSUE TITLE
Not able to import logo in Header

### ISSUE THREAD

**Issue by tu2-atmanand** [Engicos-Coders-Club/club-official-website#4]
I cant able to figure out yet what is the problem, need to research it.
See if you guys can figure it out.

**Comment by Quantaindew** [comment]
the top left logo on the chrome tab?

**Comment by tu2-atmanand** [comment]
Yeah, got it actually shreedhar solved, i was supposed to use : 
<img src={logo.src} alt="logo" className={styles.logoimg} />
