### ISSUE TITLE
feat: Footer

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#7]
Tasks
- Footer Links:
  - Home route, Team route, GEC website link, Skill survey form link
- Copiable email component
- Social media links (using Tabler Icons/React Icons)
- Copyright and credits

![image](https://github.com/Engicos-Coders-Club/club-official-website/assets/70336930/c906e9b0-8904-4fb6-ba32-5400abfcd4b3)

**Comment by Shriteen** [comment]
![Screenshot 2023-08-23 at 16-19-54 Create Next App](https://github.com/Engicos-Coders-Club/club-official-website/assets/86562935/d63cea26-3f56-4ba0-98e9-4bcbc517b90e)
@Greeshma2903 Which link is supposed to be put at made with love part?
Also what will be the Url for "our team"?

**Comment by Greeshma2903** [comment]
> ![Screenshot 2023-08-23 at 16-19-54 Create Next App](https://user-images.githubusercontent.com/86562935/262645977-d63cea26-3f56-4ba0-98e9-4bcbc517b90e.png) @Greeshma2903 Which link is supposed to be put at made with love part? Also what will be the Url for "our team"?

1. The link will be URL of this repository.
2. And the team page, a route will have to be created. I think you can leave it as text/blank link for now.
