### ISSUE TITLE
feat: Homepage project's card

### ISSUE THREAD

**Issue by Greeshma2903** [Engicos-Coders-Club/club-official-website#8]
- [ ] Section Component
- [ ] Card Component

- On hover Card: Add a border-radius
- Card elements
  - Heading
  - Desc

![image](https://github.com/Engicos-Coders-Club/club-official-website/assets/70336930/162f1af3-e623-443a-8520-0c1377505c8a)

**Comment by Quantaindew** [comment]
I'll start working on this

**Comment by Quantaindew** [comment]
HomeProjectCard component done

https://github.com/Engicos-Coders-Club/club-official-website/commit/6700fb9f490bd57fe34506ee5be6dc8a117fa051
